it('Test', () => {
    const data = {
        login: 'admin',
        password: 'sandbox24',
        courseName: 'Desafio Revvo QA',
        shortCourseName: 'Desa. Revvo'
    }

    cy.intercept('POST', '/lib/ajax/service.php*').as('servicePHP')
    cy.intercept('GET', '/lib/ajax/service-nologin.php*').as('serviceNoLogin')

    cy.visit('/')

    //Realizando login
    cy.get('.mb-4').should('have.text', 'Log in to Moodle 4.5 sandbox demo')
    cy.get('#username')
        .should('have.value', '')
        .should('have.attr', 'type', 'text')
        .should('have.attr', 'placeholder', 'Username')
        .should('have.attr', 'autocomplete', 'username')
        .type(data.login)
        .should('have.value', 'admin')
    cy.get('#password')
        .should('have.value', '')
        .should('have.attr', 'type', 'password')
        .should('have.attr', 'placeholder', 'Password')
        .should('have.attr', 'autocomplete', 'current-password')
        .type(data.password)
        .should('have.value', 'sandbox24')
    cy.get('#loginbtn')
        .should('have.attr', 'type', 'submit')
        .should('have.text', 'Log in')
        .click()

    //Aguardando as requisições da página e verificando se a página esta em inglês
    cy.wait('@servicePHP')
    cy.wait('@serviceNoLogin')
    cy.wait('@serviceNoLogin')
    cy.wait('@serviceNoLogin')
    cy.wait('@serviceNoLogin')
    cy.get('[data-key="home"] > .nav-link').should('contain', 'Home')
    cy.get('.h2').should('contain', 'Hi, Admin!')

    //Alterando a página para português
    cy.get('#user-menu-toggle')
        .should('have.attr', 'href', '#')
        .should('have.attr', 'data-toggle', 'dropdown')
        .click()
    cy.get('#carousel-item-main > .carousel-navigation-link')
        .should('have.attr', 'href', '#')
        .should('have.attr', 'role', 'menuitem')
        .should('contain', 'Language')
        .wait(1000)
        .click({ force: true })
    cy.get('[lang="pt-br"]')
        .should('have.attr', 'role', 'menuitem')
        .should('have.attr', 'href', 'https://sandbox.moodledemo.net/?lang=pt_br')
        .should('contain', 'Português')
        .should('contain', 'Brasil')
        .should('contain', '(pt_br)')
        .should('have.attr', 'lang', 'pt-br')
        .click({ force: true })
    cy.get('[data-key="home"] > .nav-link').should('contain', 'Página inicial')

    //Redirecionando para página de cursos e verificando elementos da mesma
    cy.get('[data-key="mycourses"] > .nav-link')
        .should('have.attr', 'role', 'menuitem')
        .should('have.attr', 'href', 'https://sandbox.moodledemo.net/my/courses.php')
        .should('contain', 'Meus cursos')
        .click()
    cy.get('.h2').should('have.text', 'Meus cursos')
    cy.get('#instance-33-header').should('have.text', 'Resumo dos cursos')

    //Criando um novo curso verificando todos os dados da tela
    cy.get('[action="https://sandbox.moodledemo.net/course/edit.php"] > .btn')
        .should('have.attr', 'type', 'submit')
        .should('have.text', 'Criar curso')
        .click()
    cy.get('#region-main > div > h2').should('have.text', 'Adicionar um novo curso')
    cy.get('#collapseElement-0')
        .should('have.attr', 'aria-expanded', 'true')
        .should('have.attr', 'href', '#id_generalcontainer')
        .should('have.attr', 'role', 'button')
    cy.get('.fdescription > .icon')
        .should('have.attr', 'title', 'Campo obrigatório')
        .should('have.attr', 'role', 'img')
    cy.get('#id_fullname_label')
        .should('have.attr', 'for', 'id_fullname')
        .should('contain', 'Nome completo do curso')
    cy.get('.mb-3 > span > #id_saveanddisplay')
        .should('have.attr', 'type', 'submit')
        .should('have.attr', 'name', 'saveanddisplay')
        .should('have.value', 'Salvar e mostrar')
        .click()
    cy.get('#id_error_fullname').should('contain', '- Está faltando o nome completo')
    cy.get('#id_error_shortname').should('contain', '- Está faltando o nome breve')
    cy.get('#id_fullname')
        .should('have.attr', 'type', 'text')
        .should('have.attr', 'name', 'fullname')
        .should('have.attr', 'size', '50')
        .should('have.attr', 'maxlength', '254')
        .should('have.value', '')
        .type(data.courseName)
    cy.get('#id_shortname')
        .should('have.attr', 'type', 'text')
        .should('have.attr', 'name', 'shortname')
        .should('have.attr', 'size', '20')
        .should('have.attr', 'maxlength', '100')
        .should('have.value', '')
        .type(data.shortCourseName)

    // Após preenchido, cancelado e verificado se realmente não criou o curso. 
    cy.get('.mb-3 > span > #id_cancel')
        .should('have.attr', 'type', 'submit')
        .should('have.attr', 'name', 'cancel')
        .should('have.value', 'Cancelar')
        .click()
    cy.get('[data-key="mycourses"] > .nav-link').click()
    cy.get('[action="https://sandbox.moodledemo.net/course/management.php"] > .btn')
        .should('have.attr', 'type', 'submit')
        .should('have.text', 'Gerenciar cursos')
        .click()
    cy.get('.card-body > .ml').should('not.contain', data.courseName)

    // Retornado a tela de criação, verificado se os campos foram limpos e criado o curso.
    cy.get('[data-key="mycourses"] > .nav-link').click()
    cy.get('[action="https://sandbox.moodledemo.net/course/edit.php"] > .btn').click()
    cy.get('#id_fullname')
        .should('have.value', '')
        .type(data.courseName)
    cy.get('#id_shortname')
        .should('have.value', '')
        .type(data.shortCourseName)
    cy.get('.mb-3 > span > #id_saveanddisplay').click()

    //Verifica o curso criado
    cy.get('.page-header-headings > .h2').should('have.text', data.courseName)

    //Deletar o curso criado anteriormente
    cy.get('[data-key="mycourses"] > .nav-link').click()
    cy.get('[action="https://sandbox.moodledemo.net/course/management.php"] > .btn').click()
    cy.get('.card-body > .ml').should('contain', data.courseName)
    cy.get('.action-delete > .icon')
        .eq(1)
        .click({ force: true })
    cy.get('#modal-header > h4').should('have.text', 'Confirmar')
    cy.get('#modal-body')
        .should('contain', 'Tem certeza que quer excluir completamente este curso e todos os seus dados?')
        .should('contain', `${data.courseName} (${data.shortCourseName})`)
    cy.get('[action="https://sandbox.moodledemo.net/course/management.php"] > .btn')
        .should('have.attr', 'type', 'submit')
        .should('have.text', 'Cancelar')
        .click()
    cy.get('.card-body > .ml').should('contain', data.courseName)
    cy.get('.action-delete > .icon')
        .eq(1)
        .click({ force: true })
    cy.get('[action="https://sandbox.moodledemo.net/course/delete.php"] > .btn')
        .should('have.attr', 'type', 'submit')
        .should('have.text', 'Excluir')
        .click()
    cy.get('#region-main > div > h2').should('have.text', `Cancelando ${data.shortCourseName}`)
    cy.get('[data-key="mycourses"] > .nav-link').click()
    cy.get('[action="https://sandbox.moodledemo.net/course/management.php"] > .btn')
        .should('have.attr', 'type', 'submit')
        .should('have.text', 'Gerenciar cursos')
        .click()
    cy.get('.card-body > .ml').should('not.contain', data.courseName)
})